version: "3"
services:

  postgres:
    # psql "host=0.0.0.0 port=5432 dbname=crawled_data user=defai password=rockettothemoon"
    container_name: postgres
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: defai
      POSTGRES_PASSWORD: rockettothemoon
      POSTGRES_DB: crawled_data
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
